#
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:10.18.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9b:1a:fa:4f:66:5e:ca:57:32:89:54:08:d0:23:bf:fb"
      - run: ssh-keyscan 157.245.198.103 >> ~/.ssh/know_hosts
      - run: ssh giambi@157.245.198.103
      - run: pwd

workflows:
  version: 2.1
  test:
    jobs:
      - test
      - build
