#
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10.18.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  version: 2.1
  test:
    jobs:
      - test
